// <auto-generated />
using System;
using BankCurrencyService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankCurrencyService.Data.Migrations
{
    [DbContext(typeof(BankCurrencyDbContext))]
    [Migration("20220302100834_add-rate-tables")]
    partial class addratetables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BCS")
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BankCurrencyService.Domain.Entities.Audit.Audit", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasMaxLength(301)
                        .HasColumnType("nvarchar(301)");

                    b.Property<Guid?>("CreatorKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatorUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdater")
                        .HasMaxLength(301)
                        .HasColumnType("nvarchar(301)");

                    b.Property<Guid?>("LastUpdaterKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdaterUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Audit", "BCS");
                });

            modelBuilder.Entity("BankCurrencyService.Domain.Entities.Currency.CountryCurrency", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"), 1L, 1);

                    b.Property<string>("AcronymAbb")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasMaxLength(301)
                        .HasColumnType("nvarchar(301)");

                    b.Property<Guid?>("CreatorKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatorUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdater")
                        .HasMaxLength(301)
                        .HasColumnType("nvarchar(301)");

                    b.Property<Guid?>("LastUpdaterKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdaterUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RowOrder")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("CountryCurrency", "BCS");

                    b.HasData(
                        new
                        {
                            Key = 1,
                            AcronymAbb = "AUD",
                            CountryName = "Australia Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 2,
                            AcronymAbb = "GBP",
                            CountryName = "Great Britain Pound",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 3,
                            AcronymAbb = "EUR",
                            CountryName = "Euro",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 4,
                            AcronymAbb = "JPY",
                            CountryName = "Japan Yen",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 5,
                            AcronymAbb = "CHF",
                            CountryName = "Switzerland Franc",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 6,
                            AcronymAbb = "USD",
                            CountryName = "USA Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 7,
                            AcronymAbb = "AFN",
                            CountryName = "Afghanistan Afghani",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 8,
                            AcronymAbb = "ALL",
                            CountryName = "Albania Lek",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 9,
                            AcronymAbb = "DZD",
                            CountryName = "Algeria Dinar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 10,
                            AcronymAbb = "AOA",
                            CountryName = "Angola Kwanza",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 11,
                            AcronymAbb = "ARS",
                            CountryName = "Argentina Peso",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 12,
                            AcronymAbb = "AMD",
                            CountryName = "Armenia Dram",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 13,
                            AcronymAbb = "AWG",
                            CountryName = "Aruba Florin",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 14,
                            AcronymAbb = "AUD",
                            CountryName = "Australia Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 15,
                            AcronymAbb = "ATS (EURO)",
                            CountryName = "Austria Schilling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 16,
                            AcronymAbb = "BEF (EURO)",
                            CountryName = "Belgium Franc",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 17,
                            AcronymAbb = "AZN",
                            CountryName = "Azerbaijan New Manat",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 18,
                            AcronymAbb = "BSD",
                            CountryName = "Bahamas Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 19,
                            AcronymAbb = "BHD",
                            CountryName = "Bahrain Dinar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 20,
                            AcronymAbb = "BDT",
                            CountryName = "Bangladesh Taka",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 21,
                            AcronymAbb = "BBD",
                            CountryName = "Barbados Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 22,
                            AcronymAbb = "BYR",
                            CountryName = "Belarus Ruble",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 23,
                            AcronymAbb = "BZD",
                            CountryName = "Belize Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 24,
                            AcronymAbb = "BMD",
                            CountryName = "Bermuda Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 25,
                            AcronymAbb = "BTN",
                            CountryName = "Bhutan Ngultrum",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 26,
                            AcronymAbb = "BOB",
                            CountryName = "Bolivia Boliviano",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 27,
                            AcronymAbb = "BAM",
                            CountryName = "Bosnia Mark",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 28,
                            AcronymAbb = "BWP",
                            CountryName = "Botswana Pula",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 29,
                            AcronymAbb = "BRL",
                            CountryName = "Brazil Real",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 30,
                            AcronymAbb = "GBP",
                            CountryName = "Great Britain Pound",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 31,
                            AcronymAbb = "BND",
                            CountryName = "Brunei Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 32,
                            AcronymAbb = "BGN",
                            CountryName = "Bulgaria Lev",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 33,
                            AcronymAbb = "BIF",
                            CountryName = "Burundi Franc",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 34,
                            AcronymAbb = "XOF",
                            CountryName = "CFA Franc BCEAO",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 35,
                            AcronymAbb = "XAF",
                            CountryName = "CFA Franc BEAC",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 36,
                            AcronymAbb = "XPF",
                            CountryName = "CFP Franc",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 37,
                            AcronymAbb = "KHR",
                            CountryName = "Cambodia Riel",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 38,
                            AcronymAbb = "CAD",
                            CountryName = "Canada Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 39,
                            AcronymAbb = "CVE",
                            CountryName = "Cape Verde Escudo",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 40,
                            AcronymAbb = "KYD",
                            CountryName = "Cayman Islands Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 41,
                            AcronymAbb = "CLP",
                            CountryName = "Chili Peso",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 42,
                            AcronymAbb = "CNY",
                            CountryName = "China Yuan/Renminbi",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 43,
                            AcronymAbb = "COP",
                            CountryName = "Colombia Peso",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 44,
                            AcronymAbb = "KMF",
                            CountryName = "Comoros Franc",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 45,
                            AcronymAbb = "CDF",
                            CountryName = "Congo Franc",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 46,
                            AcronymAbb = "CRC",
                            CountryName = "Costa Rica Colon",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 47,
                            AcronymAbb = "HRK",
                            CountryName = "Croatia Kuna",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 48,
                            AcronymAbb = "CUC",
                            CountryName = "Cuba Convertible Peso",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 49,
                            AcronymAbb = "CUP",
                            CountryName = "Cuba Peso",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 50,
                            AcronymAbb = "CYP (EURO)",
                            CountryName = "Cyprus Pound",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 51,
                            AcronymAbb = "CZK",
                            CountryName = "Czech Koruna",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 52,
                            AcronymAbb = "DKK",
                            CountryName = "Denmark Krone",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 53,
                            AcronymAbb = "DJF",
                            CountryName = "Djibouti Franc",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 54,
                            AcronymAbb = "DOP",
                            CountryName = "Dominican Republich Peso",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 55,
                            AcronymAbb = "XCD",
                            CountryName = "East Caribbean Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 56,
                            AcronymAbb = "EGP",
                            CountryName = "Egypt Pound",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 57,
                            AcronymAbb = "SVC",
                            CountryName = "El Salvador Colon",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 58,
                            AcronymAbb = "EEK (EURO)",
                            CountryName = "Estonia Kroon",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 59,
                            AcronymAbb = "ETB",
                            CountryName = "Ethiopia Birr",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 60,
                            AcronymAbb = "EUR",
                            CountryName = "Euro",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 61,
                            AcronymAbb = "FKP",
                            CountryName = "Falkland Islands Pound",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 62,
                            AcronymAbb = "FIM (EURO)",
                            CountryName = "Finland Markka",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 63,
                            AcronymAbb = "FJD",
                            CountryName = "Fiji Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 64,
                            AcronymAbb = "GMD",
                            CountryName = "Gambia Dalasi",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 65,
                            AcronymAbb = "GEL",
                            CountryName = "Georgia Lari",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 66,
                            AcronymAbb = "DMK (EURO)",
                            CountryName = "Germany Mark",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 67,
                            AcronymAbb = "GHS",
                            CountryName = "Ghana New Cedi",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 68,
                            AcronymAbb = "GIP",
                            CountryName = "Gibraltar Pound",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 69,
                            AcronymAbb = "GRD (EURO)",
                            CountryName = "Greece Drachma",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 70,
                            AcronymAbb = "GTQ",
                            CountryName = "Guatemala Quetzal",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 71,
                            AcronymAbb = "GNF",
                            CountryName = "Guinea Franc",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 72,
                            AcronymAbb = "GYD",
                            CountryName = "Guyana Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 73,
                            AcronymAbb = "HTG",
                            CountryName = "Haiti Gourde",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 74,
                            AcronymAbb = "HNL",
                            CountryName = "Honduras Lempira",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 75,
                            AcronymAbb = "HKD",
                            CountryName = "Hong Kong Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 76,
                            AcronymAbb = "HUF",
                            CountryName = "Hungary Forint",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 77,
                            AcronymAbb = "ISK",
                            CountryName = "Iceland Krona",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 78,
                            AcronymAbb = "INR",
                            CountryName = "India Rupee",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 79,
                            AcronymAbb = "IDR",
                            CountryName = "Indonesia Rupiah",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 80,
                            AcronymAbb = "IRR",
                            CountryName = "Iran Rial",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 81,
                            AcronymAbb = "IQD",
                            CountryName = "Iraq Dinar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 82,
                            AcronymAbb = "IED (EURO)",
                            CountryName = "Ireland Pound",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 83,
                            AcronymAbb = "ILS",
                            CountryName = "Israel New Shekel",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 84,
                            AcronymAbb = "ITL (EURO)",
                            CountryName = "Italy Lira",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 85,
                            AcronymAbb = "JMD",
                            CountryName = "Jamaica Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 86,
                            AcronymAbb = "JPY",
                            CountryName = "Japan Yen",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 87,
                            AcronymAbb = "JOD",
                            CountryName = "Jordan Dinar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 88,
                            AcronymAbb = "KZT",
                            CountryName = "Kazakhstan Tenge",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 89,
                            AcronymAbb = "KES",
                            CountryName = "Kenya Shilling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 90,
                            AcronymAbb = "KWD",
                            CountryName = "Kuwait Dinar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 91,
                            AcronymAbb = "KGS",
                            CountryName = "Kyrgyzstan Som",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 92,
                            AcronymAbb = "LAK",
                            CountryName = "Laos Kip",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 93,
                            AcronymAbb = "LVL (EURO)",
                            CountryName = "Latvia Lats",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 94,
                            AcronymAbb = "LBP",
                            CountryName = "Lebanon Pound",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 95,
                            AcronymAbb = "LSL",
                            CountryName = "Lesotho Loti",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 96,
                            AcronymAbb = "LRD",
                            CountryName = "Liberia Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 97,
                            AcronymAbb = "LYD",
                            CountryName = "Libya Dinar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 98,
                            AcronymAbb = "LTL (EURO)",
                            CountryName = "Lithuania Litas",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 99,
                            AcronymAbb = "LUF (EURO)",
                            CountryName = "Luxembourg Franc",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 100,
                            AcronymAbb = "MOP",
                            CountryName = "Macau Pataca",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 101,
                            AcronymAbb = "MKD",
                            CountryName = "Macedonia Denar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 102,
                            AcronymAbb = "MGA",
                            CountryName = "Malagasy Ariary",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 103,
                            AcronymAbb = "MWK",
                            CountryName = "Malawi Kwacha",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 104,
                            AcronymAbb = "MYR",
                            CountryName = "Malaysia Ringgit",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 105,
                            AcronymAbb = "MVR",
                            CountryName = "Maldives Rufiyaa",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 106,
                            AcronymAbb = "MTL (EURO)",
                            CountryName = "Malta Lira",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 107,
                            AcronymAbb = "MRO",
                            CountryName = "Mauritania Ouguiya",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 108,
                            AcronymAbb = "MUR",
                            CountryName = "Mauritius Rupee",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 109,
                            AcronymAbb = "MXN",
                            CountryName = "Mexico Peso",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 110,
                            AcronymAbb = "MDL",
                            CountryName = "Moldova Leu",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 111,
                            AcronymAbb = "MNT",
                            CountryName = "Mongolia Tugrik",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 112,
                            AcronymAbb = "MAD",
                            CountryName = "Morocco Dirham",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 113,
                            AcronymAbb = "MZN",
                            CountryName = "Mozambique New Metical",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 114,
                            AcronymAbb = "MMK",
                            CountryName = "Myanmar Kyat",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 115,
                            AcronymAbb = "ANG",
                            CountryName = "NL Antilles Guilder",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 116,
                            AcronymAbb = "NAD",
                            CountryName = "Namibia Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 117,
                            AcronymAbb = "NPR",
                            CountryName = "Nepal Rupee",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 118,
                            AcronymAbb = "NLG (EURO)",
                            CountryName = "Netherlands Guilder",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 119,
                            AcronymAbb = "NZD",
                            CountryName = "New Zealand Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 120,
                            AcronymAbb = "NIO",
                            CountryName = "Nicaragua Cordoba Oro",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 121,
                            AcronymAbb = "NGN",
                            CountryName = "Nigeria Naira",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 122,
                            AcronymAbb = "KPW",
                            CountryName = "North Korea Won",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 123,
                            AcronymAbb = "NOK",
                            CountryName = "Norway Kroner",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 124,
                            AcronymAbb = "OMR",
                            CountryName = "Oman Rial",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 125,
                            AcronymAbb = "PKR",
                            CountryName = "Pakistan Rupee",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 126,
                            AcronymAbb = "PAB",
                            CountryName = "Panama Balboa",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 127,
                            AcronymAbb = "PGK",
                            CountryName = "Papua New Guinea Kina",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 128,
                            AcronymAbb = "PYG",
                            CountryName = "Paraguay Guarani",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 129,
                            AcronymAbb = "PEN",
                            CountryName = "Peru Nuevo Sol",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 130,
                            AcronymAbb = "PHP",
                            CountryName = "Philippines Peso",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 131,
                            AcronymAbb = "PLN",
                            CountryName = "Poland Zloty",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 132,
                            AcronymAbb = "PTE (EURO)",
                            CountryName = "Portugal Escudo",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 133,
                            AcronymAbb = "QAR",
                            CountryName = "Qatar Rial",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 134,
                            AcronymAbb = "RON",
                            CountryName = "Romania New Lei",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 135,
                            AcronymAbb = "RUB",
                            CountryName = "Russia Rouble",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 136,
                            AcronymAbb = "RWF",
                            CountryName = "Rwanda Franc",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 137,
                            AcronymAbb = "WST",
                            CountryName = "Samoa Tala",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 138,
                            AcronymAbb = "STD",
                            CountryName = "Sao Tome/Principe Dobra",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 139,
                            AcronymAbb = "SAR",
                            CountryName = "Saudi Arabia Riyal",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 140,
                            AcronymAbb = "RSD",
                            CountryName = "Serbia Dinar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 141,
                            AcronymAbb = "SCR",
                            CountryName = "Seychelles Rupee",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 142,
                            AcronymAbb = "SLL",
                            CountryName = "Sierra Leone Leone",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 143,
                            AcronymAbb = "SGD",
                            CountryName = "Singapore Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 144,
                            AcronymAbb = "SKK (EURO)",
                            CountryName = "Slovakia Koruna",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 145,
                            AcronymAbb = "SIT (EURO)",
                            CountryName = "Slovenia Tolar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 146,
                            AcronymAbb = "SBD",
                            CountryName = "Solomon Islands Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 147,
                            AcronymAbb = "SOS",
                            CountryName = "Somali Shilling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 148,
                            AcronymAbb = "ZAR",
                            CountryName = "South Africa Rand",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 149,
                            AcronymAbb = "KRW",
                            CountryName = "South Korea Won",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 150,
                            AcronymAbb = "ESP (EURO)",
                            CountryName = "Spain Peseta",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 151,
                            AcronymAbb = "LKR",
                            CountryName = "Sri Lanka Rupee",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 152,
                            AcronymAbb = "SHP",
                            CountryName = "St Helena Pound",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 153,
                            AcronymAbb = "SDG",
                            CountryName = "Sudan Pound",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 154,
                            AcronymAbb = "SRD",
                            CountryName = "Suriname Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 155,
                            AcronymAbb = "SZL",
                            CountryName = "Swaziland Lilangeni",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 156,
                            AcronymAbb = "SEK",
                            CountryName = "Sweden Krona",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 157,
                            AcronymAbb = "CHF",
                            CountryName = "Switzerland Franc",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 158,
                            AcronymAbb = "SYP",
                            CountryName = "Syria Pound",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 159,
                            AcronymAbb = "TWD",
                            CountryName = "Taiwan Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 160,
                            AcronymAbb = "TZS",
                            CountryName = "Tanzania Shilling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 161,
                            AcronymAbb = "THB",
                            CountryName = "Thailand Baht",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 162,
                            AcronymAbb = "TOP",
                            CountryName = "Tonga Pa'anga",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 163,
                            AcronymAbb = "TTD",
                            CountryName = "Trinidad/Tobago Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 164,
                            AcronymAbb = "TND",
                            CountryName = "Tunisia Dinar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 165,
                            AcronymAbb = "TRY",
                            CountryName = "Turkish New Lira",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 166,
                            AcronymAbb = "TMM",
                            CountryName = "Turkmenistan Manat",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 167,
                            AcronymAbb = "USD",
                            CountryName = "USA Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 168,
                            AcronymAbb = "UGX",
                            CountryName = "Uganda Shilling",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 169,
                            AcronymAbb = "UAH",
                            CountryName = "Ukraine Hryvnia",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 170,
                            AcronymAbb = "UYU",
                            CountryName = "Uruguay Peso",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 171,
                            AcronymAbb = "AED",
                            CountryName = "United Arab Emirates Dirham",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 172,
                            AcronymAbb = "VUV",
                            CountryName = "Vanuatu Vatu",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 173,
                            AcronymAbb = "VEB",
                            CountryName = "Venezuela Bolivar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 174,
                            AcronymAbb = "VND",
                            CountryName = "Vietnam Dong",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 175,
                            AcronymAbb = "YER",
                            CountryName = "Yemen Rial",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 176,
                            AcronymAbb = "ZMK",
                            CountryName = "Zambia Kwacha",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        },
                        new
                        {
                            Key = 177,
                            AcronymAbb = "ZWD",
                            CountryName = "Zimbabwe Dollar",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsAvailable = false,
                            RowOrder = 0
                        });
                });

            modelBuilder.Entity("BankCurrencyService.Domain.Entities.Rate.ExchangeRate", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasMaxLength(301)
                        .HasColumnType("nvarchar(301)");

                    b.Property<Guid?>("CreatorKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatorUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ExchangeRateResourceKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdater")
                        .HasMaxLength(301)
                        .HasColumnType("nvarchar(301)");

                    b.Property<Guid?>("LastUpdaterKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdaterUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ResourceDeclaredUpdateDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Key");

                    b.HasIndex("ExchangeRateResourceKey");

                    b.ToTable("ExchangeRate", "BCS");
                });

            modelBuilder.Entity("BankCurrencyService.Domain.Entities.Rate.ExchangeRateDetail", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasMaxLength(301)
                        .HasColumnType("nvarchar(301)");

                    b.Property<Guid?>("CreatorKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatorUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("ExchangeRateKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdater")
                        .HasMaxLength(301)
                        .HasColumnType("nvarchar(301)");

                    b.Property<Guid?>("LastUpdaterKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdaterUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(10,5)");

                    b.HasKey("Key");

                    b.HasIndex("ExchangeRateKey");

                    b.ToTable("ExchangeRateDetail", "BCS");
                });

            modelBuilder.Entity("BankCurrencyService.Domain.Entities.Rate.ExchangeRateResource", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .HasMaxLength(301)
                        .HasColumnType("nvarchar(301)");

                    b.Property<Guid?>("CreatorKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatorUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdater")
                        .HasMaxLength(301)
                        .HasColumnType("nvarchar(301)");

                    b.Property<Guid?>("LastUpdaterKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastUpdaterUserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResourceUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("ExchangeRateResource", "BCS");

                    b.HasData(
                        new
                        {
                            Key = new Guid("db1d8ab3-a521-4f6c-8c94-729ce1ea491d"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResourceName = "Europesn Central Bank",
                            ResourceUri = "https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml?4610f020d7463a0cd43d6828905faf2f"
                        });
                });

            modelBuilder.Entity("BankCurrencyService.Domain.Entities.Rate.ExchangeRate", b =>
                {
                    b.HasOne("BankCurrencyService.Domain.Entities.Rate.ExchangeRateResource", "ExchangeRateResource")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("ExchangeRateResourceKey");

                    b.Navigation("ExchangeRateResource");
                });

            modelBuilder.Entity("BankCurrencyService.Domain.Entities.Rate.ExchangeRateDetail", b =>
                {
                    b.HasOne("BankCurrencyService.Domain.Entities.Rate.ExchangeRate", "ExchangeRate")
                        .WithMany("ExchangeRateDetails")
                        .HasForeignKey("ExchangeRateKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExchangeRate");
                });

            modelBuilder.Entity("BankCurrencyService.Domain.Entities.Rate.ExchangeRate", b =>
                {
                    b.Navigation("ExchangeRateDetails");
                });

            modelBuilder.Entity("BankCurrencyService.Domain.Entities.Rate.ExchangeRateResource", b =>
                {
                    b.Navigation("ExchangeRates");
                });
#pragma warning restore 612, 618
        }
    }
}
